
<!--
%\VignetteEngine{knitr::rmarkdown}
%\VignetteIndexEntry{Jags example}
-->

# Jags example

```{r setup}
haveR2jags = require('R2jags', quietly=TRUE)
print(haveR2jags)
```

```{r formatData}
data('bacteria', package='MASS')
bacterianew <- bacteria
bacterianew$yInt = as.integer(bacterianew$y == "y")
levels(bacterianew$trt) <- c("placebo", "drug", "drugplus")
```


```{r glmmBUGS}
require('glmmBUGS')
bacrag <- glmmBUGS(formula = yInt ~ trt + week, 
    data = bacterianew,
    effects = "ID", modelFile = "bacteria.txt",
    family = "bernoulli",brugs=TRUE)

source("getInits.R")
startingValues = bacrag$startingValues
```

```{r runjags}
if(haveR2jags) {
  bacResult = R2jags::jags(bacrag$ragged, 
      inits=getInits,
      model.file = "bacteria.txt", n.chain = 3,
      n.iter = 600, n.burnin = 10,
      parameters = names(getInits()),
      n.thin = 4)
} else {
	bacResult = list()
}
```

```{r postprocess}  
if(haveR2jags) {
bacParams = restoreParams(bacResult$BUGSoutput,
     bacrag$ragged)
}
```

```{r results}
if(haveR2jags) {
bacsummary = summaryChain(bacParams)
  
bacsummary$betas[,c('mean', 'sd')]

checkChain(bacParams, c("intercept", "SDID"),oneFigure=TRUE)
}
```
